global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'customer-asset-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080', '10.20.1.4:8080']
        labels:
          environment: 'staging'
          region: 'southeast-asia'

  - job_name: 'job-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081', '10.20.1.5:8080']
        labels:
          environment: 'staging'
          region: 'southeast-asia'

  - job_name: 'dispatch-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8082', '10.30.1.4:8080']
        labels:
          environment: 'staging'
          region: 'central-india'

  - job_name: 'reporting-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8083', '10.30.1.5:8080']
        labels:
          environment: 'staging'
          region: 'central-india'

  - job_name: 'kafka-broker'
    static_configs:
      - targets: ['10.20.2.4:9308', 'host.docker.internal:9308']
        labels:
          environment: 'staging'
          component: 'messaging'
