global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'customer-asset-service'
    scheme: https
    metrics_path: '/customer/metrics'
    static_configs:
      - targets: ['apim-assms-staging-45ff260826.azure-api.net:443']
        labels:
          environment: 'staging'
          region: 'southeast-asia'

  - job_name: 'job-service'
    scheme: https
    metrics_path: '/jobs/metrics'
    static_configs:
      - targets: ['apim-assms-staging-45ff260826.azure-api.net:443']
        labels:
          environment: 'staging'
          region: 'southeast-asia'

  - job_name: 'dispatch-service'
    scheme: https
    metrics_path: '/dispatch/metrics'
    static_configs:
      - targets: ['apim-assms-staging-45ff260826.azure-api.net:443']
        labels:
          environment: 'staging'
          region: 'central-india'

  - job_name: 'reporting-service'
    scheme: https
    metrics_path: '/reports/metrics'
    static_configs:
      - targets: ['apim-assms-staging-45ff260826.azure-api.net:443']
        labels:
          environment: 'staging'
          region: 'central-india'
